#!/usr/bin/env python3
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Draw the status-screen animation into avatar/happy_anim.c and .h.

A bouncing, blinking blob face, drawn procedurally (no image files). The
firmware scales each art pixel up to a solid block on the ST7789 boards and
uses frame 0 on e-paper.

Usage: gen_happy_anim.py
"""

import math
import pathlib

WIDTH, HEIGHT, FRAMES, FRAME_MS = 56, 59, 30, 40
OUT = pathlib.Path(__file__).resolve().parent.parent / "avatar" / "happy_anim.c"
PALETTE = [(0, 0, 0), (16, 16, 24), (242, 239, 255), (201, 194, 230), (255, 158, 181), (127, 214, 255)]
BG, OUT_C, BODY, SHADE, CHEEK, ACCENT = range(len(PALETTE))
HEADER = [
    "// Generated by tools/gen_happy_anim.py. Do not edit.",
]


def rgb565_be(rgb):
    r, g, b = rgb
    v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    # Panel expects the most significant byte first.
    return ((v & 0xFF) << 8) | (v >> 8)


def frame(i):
    t = i / FRAMES
    px = [BG] * (WIDTH * HEIGHT)

    def disc(cx, cy, r, c):
        for y in range(HEIGHT):
            for x in range(WIDTH):
                if (x + 0.5 - cx) ** 2 + (y + 0.5 - cy) ** 2 <= r * r:
                    px[y * WIDTH + x] = c

    cx, cy = WIDTH / 2, 32 - abs(math.sin(t * math.pi)) * 6
    ring = 25 + math.sin(t * 2 * math.pi)
    disc(cx, cy, ring, ACCENT)
    disc(cx, cy, ring - 1.5, BG)
    disc(cx, cy, 21, OUT_C)
    disc(cx, cy, 20, SHADE)
    disc(cx - 1.5, cy - 1.5, 18, BODY)
    ey = int(cy - 3)
    for s in (-1, 1):
        x = int(cx) + s * 7
        # Happy closed eyes: an upturned arc.
        for dx in range(-2, 3):
            px[(ey - (1 if abs(dx) < 2 else 0)) * WIDTH + x + dx] = OUT_C
        disc(x + 0.5 + s * 2, ey + 5.5, 1.8, CHEEK)
    my = int(cy + 6)
    for dx in range(-4, 5):
        px[(my + (0 if abs(dx) == 4 else 1 if abs(dx) == 3 else 2)) * WIDTH + int(cx) + dx] = OUT_C
    return px


def main():
    lines = HEADER + [
        '#include "happy_anim.h"',
        "",
        "#if CONFIG_HOMEHUB_DISPLAY",
        "",
        f"const uint16_t happy_anim_palette[{len(PALETTE)}] = {{",
    ]
    lines += [f"    0x{rgb565_be(c):04x}," for c in PALETTE]
    lines += ["};", "", "const uint8_t happy_anim_frames[HAPPY_ANIM_FRAMES]"
              "[HAPPY_ANIM_HEIGHT * HAPPY_ANIM_WIDTH] = {"]
    for i in range(FRAMES):
        f = frame(i)
        lines.append("    {")
        for y in range(HEIGHT):
            lines.append("        " + ",".join(map(str, f[y * WIDTH:(y + 1) * WIDTH])) + ",")
        lines.append("    },")
    lines += ["};", "", "#endif", ""]
    OUT.write_text("\n".join(lines))

    OUT.with_suffix(".h").write_text("\n".join(HEADER + [
        "#pragma once",
        "",
        "#include <stdint.h>",
        '#include "sdkconfig.h"',
        "",
        f"#define HAPPY_ANIM_WIDTH     {WIDTH}",
        f"#define HAPPY_ANIM_HEIGHT    {HEIGHT}",
        f"#define HAPPY_ANIM_FRAMES    {FRAMES}",
        f"#define HAPPY_ANIM_FRAME_MS  {FRAME_MS}",
        "",
        "#if CONFIG_HOMEHUB_DISPLAY",
        f"extern const uint16_t happy_anim_palette[{len(PALETTE)}];",
        "extern const uint8_t happy_anim_frames[HAPPY_ANIM_FRAMES]"
        "[HAPPY_ANIM_HEIGHT * HAPPY_ANIM_WIDTH];",
        "#endif",
        "",
    ]))
    print(f"{OUT}: {FRAMES} frames, {len(PALETTE)} colours")


if __name__ == "__main__":
    main()
